const urlParams = new URLSearchParams(window.location.search);
const userId = urlParams.get('userId');
const displayName = urlParams.get('displayName');
const pictureUrl = urlParams.get('pictureUrl');
const statusMessage = urlParams.get('statusMessage');
document.getElementsByClassName("card-title")[0].innerHTML = `<b>${displayName}</b>`;
document.getElementsByClassName("card-subtitle")[0].textContent = userId;
document.getElementsByClassName("card-text")[0].textContent = statusMessage;
document.getElementsByClassName("profieImg")[0].src = pictureUrl;